name: quick_blue
description: A cross-platform BluetoothLE plugin for Flutter.
version: 1.0.0

publish_to: 'none'

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.4
  convert: ^3.1.1
  bluez: ^0.8.1
  collection: ^1.17.0
  logging: ^1.1.1
  quick_blue_macos:
    git:
      url: https://github.com/SandeepMalviyaSM/quick_blue_macos.git
      ref: main
  # quick_blue_windows: ^0.4.0-dev.0
  quick_blue_windows:
    git:
      url: https://github.com/SandeepMalviyaSM/quick_blue_windows.git
      ref: main

flutter:
  plugin:
    platforms:
      android:
        package: com.example.quick_blue
        pluginClass: QuickBluePlugin
      ios:
        pluginClass: QuickBluePlugin
      macos:
        default_package: quick_blue_macos
      windows:
        default_package: quick_blue_windows
      linux:
        default_package: quick_blue_linux